title:        Test Data From Google Spreadsheet
description:  Working on scripts for helping me generate and integrate with test data created in Google Spreadsheets, then published to Github as YAML for use in variety of APIs.
url:          https://101.apievangelist.com

version:      1.1.1

author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown
permalink:    pretty
pygments:     true
highlighter:  rouge

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md",".DS_Store"]

logo : https://s3.amazonaws.com/kinlane-productions/api-evangelist/api-evangelist-101.png

github_user: adopta-agency
github_repo: test-data-from-google-spreadsheets

spreadsheetkey: 1b_VQ44hGwiul7GnhQbI2zDQThk3_5p1qG-0dl9o5sr4
